export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOADING = "AUTH_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTH_VERIFIED = "AUTH_VERIFIED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
