# Generated by Django 2.2 on 2019-04-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='join_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
